name: thema_publikation

on:
  push

jobs:  

  build:

    env:
      ORG_GRADLE_PROJECT_awsAccessKey: ${{secrets.AWS_ACCESS_KEY_ID}}
      ORG_GRADLE_PROJECT_awsSecretAccessKey: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      ORG_GRADLE_PROJECT_awsRegion: ${{secrets.AWS_DEFAULT_REGION}}
      ORG_GRADLE_PROJECT_awsEndpoint: ${{secrets.AWS_ENDPOINT_URL}}

    runs-on: ubuntu-latest

    container:
      image: sogis/gretl:3.1

    steps:
      - uses: actions/checkout@v4

      - name: Run GRETL job
        run: |
          pwd
          ls -la
          gradle -b _gretl/thema_publikation/build.gradle --init-script /home/gradle/init.gradle createStammdatenSchema --no-daemon